---
title: "01_analy_data"
author: "Jagadeesh Puvvula"
date: "2026-03-12"
output: pdf_document
---

#add 7-9 year BASC outcomes
```{r}
#MIREC
mirec_basc_7y<- readxl::read_xlsx("E:/BBK17/11. BBK17_BASC DVs_July2 2024/MIREC_ENDO_Ph1_BABY_BASC3DV_Yes_to_MIREC_BBK_Aug9 2023.xlsx") |> 
  select(c(SUBJECT_ID, bascTexCD_3, bascTinCD_3, bascTasCD_3, bascTbsCD_3 )) |>
  clean_names() |>
  rename(basc_ext = basc_tex_cd_3,
         basc_int = basc_tin_cd_3,
         basc_adt = basc_tas_cd_3,
         basc_bsi = basc_tbs_cd_3) |>
  mutate(subject_id = as.factor(subject_id))

#HOME
home_basc_7y<- haven::read_sas("E:/BBK17/pj/data_2023apr/home_outcomes.sas7bdat") |>
  clean_names() |>
  filter(visit =="P3") |>
  select(1, starts_with("basc")) |>
  select(c(1,2,28:30))|>
  mutate(subject_id = as.factor(subject_id)) |>
  rename(basc_int = basc_inz)

basc_7y<- bind_rows(mirec_basc_7y, home_basc_7y) |>drop_na()

rm(home_basc_7y, mirec_basc_7y)
```


#BDI Score baseline - calculated z-scores
```{r}
home_mat_dep<- read_sas(paste0(data, "HOME_covariates.sas7bdat")) |>
  clean_names() |>
  select(c(1,23))|>
  mutate(subject_id = as.character(subject_id))|>
  rename(mat_dep = bdi_bhv) |>
  mutate(mat_dep_z = (mat_dep - mean(mat_dep, na.rm = TRUE)) / sd(mat_dep, na.rm = TRUE)) |>
  select(1,3)

#CES-D score from MIREC - calcualted z-scores
mirec_mat_dep<- read_csv("E:\\BBK17\\4. BBK17_CD+ CRF data corrections_Nov18 2022\\CDPLUS.2_NEURO.7_20221117\\MSAQ_DATA_DEPRESSION_Yes to NEURO BBK.csv") |>
  clean_names() |>
  select(c(2,20)) |>
  rename(mat_dep = cesdepq5cd)|>
  mutate(mat_dep_z = (mat_dep - mean(mat_dep, na.rm = TRUE)) / sd(mat_dep, na.rm = TRUE)) |>
  select(1,3)
```

#all participants with ~16W exposures, covariates, and limited outcomes
```{r}
home_df <- read_csv("E:/BBK17/pj/data_2023apr/all_obs/home_1trim.csv") |> 
  select(-c(32:41)) |> 
  mutate(
    pb = pb*10,
    subject_id = as.character(subject_id),
    center = "999",
    cohort = "1"
  ) |>
  mutate_if(is.numeric, ~ round(., 3)) |>
  rename_all(~ str_replace(., "(_sg|sg|_lp)", "")) |>
  rename(race = race_cd,
         mom_age = mom_age_deliv) |>    
  left_join(home_mat_dep, by = "subject_id") |>
  select(
    subject_id,
    pb, hg, dma,
    dde, pbde47, pcb118, pcb138, pcb153, pcb180,
    pfhxs, pfoa, pfos,
    bcetp, bdcpp, dbup, dphp,
    tcs, bpa,
    mbp, mbzp, mcpp, dehp, mep, mibp,
    op_de, op_dm,
    b_pb, m_pb, p_pb,
    cotinine,
    sex, race, parity_n, mom_age, edu3,
    home_score_total, mat_dep_z,
    center, cohort
  )

mirec_df <- read_csv("E:/BBK17/pj/data_2023apr/all_obs/mirec_1trim.csv") |>
  select(-c(29:36)) |>
  clean_names() |>
  rename_all(~ str_replace(., "(_sg|sg|_lp)", "")) |>
  rename(
    pfhxs = pf_hx_spl,
    pfoa  = pfoapl,
    pfos  = pfospl
  ) |>
  mutate(
    subject_id = as.character(subject_id),
    center = str_sub(subject_id, 1, 2),
    cohort = "2"
  ) |>
  left_join(mirec_mat_dep, by = "subject_id") |>
  select(
    subject_id,
    pb, hg, dma,
    dde, pbde47, pcb118, pcb138, pcb153, pcb180,
    pfhxs, pfoa, pfos,
    bcetp, bdcpp, dbup, dphp,
    tcs, bpa,
    mbp, mbzp, mcpp, dehp, mep, mibp,
    op_de, op_dm,
    b_pb, m_pb, p_pb,
    cotinine,
    sex, race, parity_n, mom_age, edu3,
    home_score_total, mat_dep_z,
    center, cohort
  )

combined_data<- bind_rows(mirec_df, home_df)

combined_data<- combined_data |>
  rename(sigma_DEHP=dehp, di_Ethyl_OP=op_de, di_Methyl_OP=op_dm, 
         bcep = bcetp, bdcipp=bdcpp, dnbp=dbup)|>
  rename_at(vars(2:30), toupper) |>
  rename(Pb=PB, Hg=HG,
          "Butyl paraben" = B_PB ,  "Methyl paraben" = M_PB, "Propyl paraben"= P_PB,
         "Di-ethyl organophosphate" = DI_ETHYL_OP, "Di-methyl organophosphate" = DI_METHYL_OP,
         "Triclosan" = TCS,  "Bisphenol-A" =BPA) |>
  mutate(cohort = ifelse(cohort == "1", "HOME", "MIREC")) |>
  select(c(
    subject_id,
    Pb, Hg, DMA, 
    DDE, PBDE47, PCB118, PCB138, PCB153, PCB180,
    PFHXS, PFOA, PFOS,
    BCEP, BDCIPP, DNBP, DPHP,
    Triclosan, "Bisphenol-A", 
    MBP, MBZP, MCPP, SIGMA_DEHP, MEP, MIBP,
    "Di-ethyl organophosphate", "Di-methyl organophosphate",
    "Butyl paraben", "Methyl paraben", "Propyl paraben",
    cotinine,
    sex, race, parity_n, mom_age, edu3, home_score_total,
    mat_dep_z,
    center, cohort
    )) |>
  mutate(subject_id = as.factor(subject_id))
```

#join BASC 7Y outcomes with exposure and covariate
```{r}
analy_df<- full_join(
  combined_data, basc_7y, by = "subject_id"
  ) |>
  mutate(cohort = if_else(is.na(cohort), "MIREC", cohort)) |>
  rename(BASC_BSI = basc_bsi,
         BASC_EXT = basc_ext,
         BASC_INT = basc_int,
         BASC_ADT = basc_adt)

write_csv(analy_df, "E:/BBK17/pj/basc_7y/data/basc_7y_df.csv")
```

#visualize missing data (n=535 all with outcome data)
```{r}
# Define the desired order for y-axis labels
custom_order <- rev(c(
  "Pb", "Hg", "DMA",
  "DDE", "PBDE47", "PCB118", "PCB138", "PCB153", "PCB180",
  "PFHXS", "PFOA", "PFOS", 
  "BCEP", "BDCIPP", "DNBP", "DPHP", 
  "Triclosan", "Bisphenol-A", 
  "MBP", "MBZP", "MCPP", "SIGMA DEHP", "MEP", "MIBP", 
  "Di-ethyl organophosphate", "Di-methyl organophosphate",
  "Butyl paraben", "Methyl paraben", "Propyl paraben", 
  "BASC_BSI", "BASC_EXT", "BASC_INT", "BASC_ADT",
  "cotinine", "sex", "race", "parity_n",  "mom_age", "edu3",
  "home_score_total", "mat_dep_z"))


# Assuming combined_data is your dataset
missing_data <- is.na(analy_df)
missing_data_df <- as.data.frame(missing_data)

# Adding row numbers as a column
missing_data_df$Observations <- seq_len(nrow(missing_data_df))

# Converting the data to long format
missing_data_long <- pivot_longer(
  missing_data_df,
  cols = -Observations,
  names_to = "Variables",
  values_to = "Missing"
)

# Calculate percentage of missing values per variable
missing_percentage <- missing_data_long |>
  group_by(Variables) |>
  summarize(MissingPercentage = mean(Missing, na.rm = TRUE) * 100) |>
  arrange(desc(MissingPercentage))

missing_data_long_filtered <- missing_data_long |>
  filter(!is.na(Variables)) |>
  mutate(Variables = factor(Variables, levels = custom_order)) |>
  mutate(Missing = factor(Missing))|>
  mutate(Missing = recode(Missing, "TRUE" = "Unmeasured", "FALSE" = "Measured")) |>
  drop_na()

# Remaining code for creating the heatmap with ggplot
ggplot(missing_data_long_filtered, aes(x = Observations, y = reorder(Variables, -as.numeric(Missing)), fill = Missing)) +
  geom_tile() +
  scale_fill_manual(values = c("Unmeasured" = "royalblue", "Measured" = "gray90")) +
  labs(title = "", x = "", y = "Variables") +
  theme_bw() +
  theme(
    legend.position = "bottom",
    axis.text.x = element_blank(),  # Remove x-axis text
    axis.ticks.x = element_blank(),
    panel.border = element_blank(),
    panel.grid.major = element_blank(),
    panel.grid.minor = element_blank(),
    axis.line = element_line(colour = "black"),
    legend.key.width = unit(0.8, "cm"),
    legend.key.height = unit(0.3, "cm")
  ) +
  geom_vline(xintercept = 1933, color = "grey20", linetype = "solid", linewidth = 1.5) +
  guides(fill = guide_legend(direction = "horizontal",  title.hjust = 0.5, title="")) +
  scale_y_discrete(labels = function(x) paste0(x, " (", round(missing_percentage$MissingPercentage[match(x, missing_percentage$Variables)], 1), "%)"))
```

#save missing data
```{r}
ggsave("E:/BBK17/pj/basc_7y/results/missing_pattern_full_data.tiff", 
       width = 8,height = 6,
       dpi=300)
```



